### ISSUE TITLE
Using to retrieve name and email from a webservice

### ISSUE THREAD

**Issue by Ridermansb** [nripendra/Resty.Net#1]
Supports WebService? How to read a WebService? 

Need to retrieve the name and email of the following webservice: `http://{{url}}.asmx?op=consultCustomer` _(I just url)_

Must pass registration id: eg 12345

**Comment by nripendra** [comment]
@Ridermansb not quite sure what your question is, but yes it should support webservice as well. Normally webservices uses SOAP formats, which means you'll have to pass the request to server enclosed in SOAP envelopes. 

Is this REST full webservice?

**Comment by Ridermansb** [comment]
Yep, I managed to make it work. My mistake. thank you
